### ISSUE TITLE
Convert to Gradle

### ISSUE THREAD

**Issue by rslavin** [rslavin/PoliDroid-AS#3]
Currently, Maven is used to reduce the repository size. Unfortunately, Maven does not mesh well with Idea Plugins. Recently, support for Gradle has been added which could make handling the CoreNLP dependencies quite a bit easier. See the link below for more info.

https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html

**Comment by chris414862** [comment]
The gradle migration branch is now converted to gradle
